server:
  port: 9898
logging:
  root:
    level: debug
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://120.48.94.210:3306/website?characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    username: ENC(kPKnRADlut5UtUqytqnh9g==)
    password: ENC(2AgKiQfCMd1L87szsCXiRA==)
  # 解决swagger无法启动问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    # 配置MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 配置MyBatis-Plus操作表的默认前缀
      table-prefix: tf_
# jasypt信息加密
jasypt:
  encryptor:
    password: simon_123456