server:
  port: 9898
logging:
  root:
    level: debug
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://120.48.94.210:3306/website?characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    username: ENC(kPKnRADlut5UtUqytqnh9g==)
    password: ENC(2AgKiQfCMd1L87szsCXiRA==)
    #连接池
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 120000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # 解决swagger无法启动问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    # 设置dispatcherServlet在项目启动时就加载 ，而不是懒加载
    servlet:
      load-on-startup: 1
  redis:
    host: 192.168.0.102
    port: 6379
    password: redis
mybatis-plus:
  configuration:
    # 配置MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 配置MyBatis-Plus操作表的默认前缀
      table-prefix: tf_
  mapper-locations: classpath:mapper/**/*.xml
# jasypt信息加密
jasypt:
  encryptor:
    password: simon_123456
aliyun:
  accessKeyId: LTAI5tJxsss5X8DLYjvbXgYs
  accessKeySecret: D8HCMFrwz2mDgVI62Z6HhU31NBOv6k
wx:
  appid: wxd853562a0548a7d0
  secret: 4a5d5615f93f24bdba2ba8534642dbb6
  get_accessToken_url: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code